id: core
templates:

- id: menu
  scene: res://core/menu/menu.tscn
  inputs: [ select, cancel ]
  events:
    terminal-select: terminal
    closed: terminal

- id: dialog-cutscene
  scene: res://core/dialog-cutscene/dialog-cutscene.tscn
  inputs: [ advance, skip ]
  events:
    dialog-event: inactive
    terminal-frame: terminal
    begin-block: active
    end-block: active

- id: landmark-overworld
  scene: res://core/landmark-overworld/landmark-overworld.tscn
  inputs: [ select ]
  events:
    navigate: active
