id: core
templates:

  menu:
    scene: res://modules/core/menu/menu.tscn
    inputs: [ select, cancel ]
    outputs:
      terminal-select:
        default: to-parent
        allowed: [ to-sibling, to-parent ]
      closed:
        default: to-parent
        allowed: [ to-sibling, to-parent ]

  dialog-cutscene:
    scene: res://modules/core/dialog-cutscene/dialog-cutscene.tscn
    inputs: [ advance, skip ]
    outputs:
      dialog-interaction:
        default: to-parent
        allowed: [ to-sibling, to-child, to-parent ]
      terminal-frame:
        default: to-parent
        allowed: [ to-sibling, to-parent ]

  landmark-overworld:
    scene: res://modules/core/landmark-overworld/landmark-overworld.tscn
    inputs: [ select ]
    outputs:
      navigate:
        default: to-self
        allowed: [ to-sibling, to-child, to-parent, to-self ]